In [8]:
import io
import numpy as np
from scipy import optimize
import pandas as pd
import matplotlib.pyplot as plt
import math
%matplotlib qt

In [9]:
def original(T, a_0, a_12, a_1, b_12, b_1, b_32):
    upper  = a_0 + (a_12)*(T**(1/2)) + a_1*T
    lower = T**(1/6) + (b_12)*(T**(1/2)) + (b_1)*(T) + (b_32)*(T**(3/2))
    value = upper/lower
    return value

In [10]:
def new(T, a, b, gamma):
    value = a * ((T/300)**b) * np.exp(-gamma/T)
    return value

In [11]:
temps = np.logspace(0, 4, 3000)

 C + H3+  ->  CH+ + H2
 Measured from 72 k to 10^4 K

In [12]:
temps

array([1.00000000e+00, 1.00307586e+00, 1.00616118e+00, ...,
       9.93876551e+03, 9.96933574e+03, 1.00000000e+04])

In [13]:
rates = []
for temp in temps:
    rate = original(temp, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates.append(rate)

In [14]:
plt.plot(temps, rates)
plt.xscale("log")
plt.yscale("log")

In [15]:
popt, pcov = optimize.curve_fit(new, temps, rates, method="lm")
perr = np.sqrt(np.diag(pcov))
print (popt)
print (perr)

[ 7.71813334e-10  3.58482490e-02 -6.54497243e-01]
[1.24186718e-12 7.42127195e-04 8.34693347e-03]


In [16]:
fit_rates = []
for temp in temps:
    fit_rate = new(temp, popt[0], popt[1], popt[2])
    fit_rates.append(fit_rate)

In [ ]:
#plt.plot(temps, fit_rates, label = "fit")
#plt.plot(temps, rates, label = "original")
#num = float(fit_rates - rates)/float(rates)
percent = []
for char in range(len(fit_rates)):
    num = (fit_rates[char] - rates[char])/rates[char]
    percent.append(num)
plt.plot(temps, percent)
plt.xscale("log")
#plt.yscale("log")
plt.legend()

In [18]:
#fitting 2 curves
temps1 = np.logspace(0, 2, 1500)
temps2 = np.logspace(2, 4, 1500)

rates1 = []
rates2 = []

for temp1 in temps1:
    rate1 = original(temp1, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates1.append(rate1)

for temp2 in temps2:
    rate2 = original(temp2, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates2.append(rate2)

popt1, pcov1 = optimize.curve_fit(new, temps1, rates1, method="lm")
perr1 = np.sqrt(np.diag(pcov1))
print (popt1)
print (perr1)

popt2, pcov2 = optimize.curve_fit(new, temps2, rates2, method="lm")
perr2 = np.sqrt(np.diag(pcov2))
print (popt2)
print (perr2)


[ 6.05580803e-10 -7.20058584e-02 -1.57173917e-01]
[7.32495237e-13 4.43915850e-04 2.09456879e-03]
[ 6.58007596e-10  1.18558086e-01 -1.69816656e+01]
[5.07341157e-13 3.05720919e-04 1.78188538e-01]


In [96]:
fit_rates1 = []
for temp1 in temps1:
    fit_rate1 = new(temp1, popt1[0], popt1[1], popt1[2])
    fit_rates1.append(fit_rate1)
    
fit_rates2 = []
for temp2 in temps2:
    fit_rate2 = new(temp2, popt2[0], popt2[1], popt2[2])
    fit_rates2.append(fit_rate2)

In [98]:
plt.plot(temps1, fit_rates1, label = "fit1")
plt.plot(temps2, fit_rates2, label = "fit2")
plt.plot(temps, rates, label = "original")
plt.xscale("log")
plt.yscale("log")
plt.legend()

In [15]:
#fitting 4 curves
temps1 = np.logspace(0, 1, 1500)
temps2 = np.logspace(1, 2, 1500)
temps3 = np.logspace(2, 3, 1500)
temps4 = np.logspace(3, 4, 1500)

rates1 = []
rates2 = []
rates3 = []
rates4 = []


for temp1 in temps1:
    rate1 = original(temp1, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates1.append(rate1)
for temp2 in temps2:
    rate2 = original(temp2, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates2.append(rate2)
for temp3 in temps3:
    rate3 = original(temp3, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates3.append(rate3)
for temp4 in temps4:
    rate4 = original(temp4, 1.0218E-09, 7.2733E-11, 5.9203E-14, 4.4914E-02, -2.6056E-04, 2.6397E-06)
    rates4.append(rate4)

popt1, pcov1 = optimize.curve_fit(new, temps1, rates1, method="lm")
perr1 = np.sqrt(np.diag(pcov1))
print (popt1)
print (perr1)

popt2, pcov2 = optimize.curve_fit(new, temps2, rates2, method="lm")
perr2 = np.sqrt(np.diag(pcov2))
print (popt2)
print (perr2)

popt3, pcov3 = optimize.curve_fit(new, temps3, rates3, method="lm")
perr3 = np.sqrt(np.diag(pcov3))
print (popt3)
print (perr3)

popt4, pcov4 = optimize.curve_fit(new, temps4, rates4, method="lm")
perr4 = np.sqrt(np.diag(pcov4))
print (popt4)
print (perr4)

[ 5.29383261e-10 -1.11228774e-01 -5.04713116e-02]
[2.72598175e-13 1.42203834e-04 3.62869015e-04]
[ 6.55013599e-10 -1.91617164e-02 -1.12962463e+00]
[2.31495192e-13 2.67833507e-04 6.98802342e-03]
[ 6.64182677e-10  1.04723454e-01 -1.43885024e+01]
[1.81644628e-13 2.42335915e-04 6.56006102e-02]
[7.56323508e-10 7.79803428e-02 9.11712799e+01]
[1.90747607e-12 7.38902078e-04 2.04543796e+00]


In [16]:
fit_rates1 = []
for temp1 in temps1:
    fit_rate1 = new(temp1, popt1[0], popt1[1], popt1[2])
    fit_rates1.append(fit_rate1)
    
fit_rates2 = []
for temp2 in temps2:
    fit_rate2 = new(temp2, popt2[0], popt2[1], popt2[2])
    fit_rates2.append(fit_rate2)

fit_rates3 = []
for temp3 in temps3:
    fit_rate3 = new(temp3, popt3[0], popt3[1], popt3[2])
    fit_rates3.append(fit_rate3)

fit_rates4 = []
for temp4 in temps4:
    fit_rate4 = new(temp4, popt4[0], popt4[1], popt4[2])
    fit_rates4.append(fit_rate4)

In [17]:
plt.plot(temps1, fit_rates_1, label = "fit1")
plt.plot(temps2, fit_rates2, label = "fit2")
plt.plot(temps3, fit_rates3, label = "fit3")
plt.plot(temps4, fit_rates4, label = "fit4")
#plt.plot(temps, rates, label = "original")
plt.xscale("log")
plt.yscale("log")
plt.legend()

NameError: name 'fit_rates_1' is not defined

In [114]:
percent1 = []
for char1 in range(len(fit_rates1)):
    num1 = (fit_rates1[char1] - rates1[char1])/rates1[char1]
    percent1.append(num1)
percent2 = []
for char2 in range(len(fit_rates2)):
    num2 = (fit_rates2[char2] - rates2[char2])/rates2[char2]
    percent2.append(num2)
percent3 = []
for char3 in range(len(fit_rates3)):
    num3 = (fit_rates3[char3] - rates3[char3])/rates3[char3]
    percent3.append(num3)
percent4 = []
for char4 in range(len(fit_rates4)):
    num4 = (fit_rates4[char4] - rates4[char4])/rates4[char4]
    percent4.append(num4)
    
plt.plot(temps1, percent1, label = "fit1")
plt.plot(temps2, percent2, label = "fit2")
plt.plot(temps3, percent3, label = "fit3")
plt.plot(temps4, percent4, label = "fit4") 
plt.xscale("log")