In [2]:
import io
import numpy as np
from scipy import optimize
import pandas as pd
import matplotlib.pyplot as plt
import math
%matplotlib qt

In [3]:
def original(T, a_0, a_12, a_1, b_12, b_1, b_32):
    upper  = a_0 + (a_12)*(T**(1/2)) + a_1*T
    lower = T**(1/6) + (b_12)*(T**(1/2)) + (b_1)*(T) + (b_32)*(T**(3/2))
    value = upper/lower
    return value

In [4]:
def new(T, a, b, gamma):
    value = a * ((T/300)**b) * np.exp(-gamma/T)
    return value

In [5]:
temps = np.logspace(0, 4, 3000)

 C + H3+  ->  CH2+ + H
 Measured from 72 k to 10^4 K

In [6]:
temps

array([1.00000000e+00, 1.00307586e+00, 1.00616118e+00, ...,
       9.93876551e+03, 9.96933574e+03, 1.00000000e+04])

In [7]:
rates = []
for temp in temps:
    rate = original(temp, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates.append(rate)

In [8]:
plt.plot(temps, rates)
plt.xscale("log")
plt.yscale("log")

In [9]:
popt, pcov = optimize.curve_fit(new, temps, rates, method="lm")
perr = np.sqrt(np.diag(pcov))
print (popt)
print (perr)

[ 3.18662983e-10 -1.78650414e-01  4.97271568e-02]
[2.26035107e-13 2.82551866e-04 2.09910946e-03]


In [10]:
fit_rates = []
for temp in temps:
    fit_rate = new(temp, popt[0], popt[1], popt[2])
    fit_rates.append(fit_rate)

In [11]:
plt.plot(temps, fit_rates, label = "fit")
plt.plot(temps, rates, label = "original")
plt.xscale("log")
plt.yscale("log")
plt.legend()

In [12]:
percent = []
for char in range(len(fit_rates)):
    num = (fit_rates[char] - rates[char])/rates[char]
    percent.append(num)
plt.plot(temps, percent)
plt.xscale("log")
#plt.yscale("log")
plt.legend()

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


In [13]:
#fitting 2 curves
temps1 = np.logspace(0, 3, 1500)
temps2 = np.logspace(3, 4, 1500)

rates1 = []
rates2 = []

for temp1 in temps1:
    rate1 = original(temp1, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates1.append(rate1)

for temp2 in temps2:
    rate2 = original(temp2, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates2.append(rate2)

popt1, pcov1 = optimize.curve_fit(new, temps1, rates1, method="lm")
perr1 = np.sqrt(np.diag(pcov1))
print (popt1)
print (perr1)

popt2, pcov2 = optimize.curve_fit(new, temps2, rates2, method="lm")
perr2 = np.sqrt(np.diag(pcov2))
print (popt2)
print (perr2)


[ 3.26861968e-10 -1.68304797e-01  4.41413316e-03]
[2.41077303e-14 2.93603670e-05 1.80545322e-04]
[ 6.25759460e-10 -4.28319281e-01  3.66065039e+02]
[3.34590043e-12 1.64561753e-03 3.98959649e+00]


In [67]:
fit_rates1 = []
for temp1 in temps1:
    fit_rate1 = new(temp1, popt1[0], popt1[1], popt1[2])
    fit_rates1.append(fit_rate1)
    
fit_rates2 = []
for temp2 in temps2:
    fit_rate2 = new(temp2, popt2[0], popt2[1], popt2[2])
    fit_rates2.append(fit_rate2)

In [68]:
plt.plot(temps1, fit_rates1, label = "fit1")
plt.plot(temps2, fit_rates2, label = "fit2")
plt.plot(temps, rates, label = "original")
plt.xscale("log")
plt.yscale("log")
plt.legend()

In [70]:
percent1 = []
for char1 in range(len(fit_rates1)):
    num1 = (fit_rates1[char1] - rates1[char1])/rates1[char1]
    percent1.append(num1)
percent2 = []
for char2 in range(len(fit_rates2)):
    num2 = (fit_rates2[char2] - rates2[char2])/rates2[char2]
    percent2.append(num2)

plt.plot(temps1, percent1, label = "fit1")
plt.plot(temps2, percent2, label = "fit2")
plt.xscale("log")

In [41]:
#fitting 4 curves
temps1 = np.logspace(0, 1, 1500)
temps2 = np.logspace(1, 2, 1500)
temps3 = np.logspace(2, 3, 1500)
temps4 = np.logspace(3, 4, 1500)

rates1 = []
rates2 = []
rates3 = []
rates4 = []


for temp1 in temps1:
    rate1 = original(temp1, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates1.append(rate1)
for temp2 in temps2:
    rate2 = original(temp2, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates2.append(rate2)
for temp3 in temps3:
    rate3 = original(temp3, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates3.append(rate3)
for temp4 in temps4:
    rate4 = original(temp4, 8.5145E-10, 0, 0, 9.5666E-04, -4.4040E-05, 2.3496E-06)
    rates4.append(rate4)

popt1, pcov1 = optimize.curve_fit(new, temps1, rates1, method="lm")
perr1 = np.sqrt(np.diag(pcov1))
print (popt1)
print (perr1)

popt2, pcov2 = optimize.curve_fit(new, temps2, rates2, method="lm")
perr2 = np.sqrt(np.diag(pcov2))
print (popt2)
print (perr2)

popt3, pcov3 = optimize.curve_fit(new, temps3, rates3, method="lm")
perr3 = np.sqrt(np.diag(pcov3))
print (popt3)
print (perr3)

popt4, pcov4 = optimize.curve_fit(new, temps4, rates4, method="lm")
perr4 = np.sqrt(np.diag(pcov4))
print (popt4)
print (perr4)

[ 5.69260391e-10 -7.19149586e-02 -7.67757134e-02]
[4.21129260e-13 2.05015105e-04 5.28164060e-04]
[ 7.59711154e-10  5.22105322e-02 -1.51804569e+00]
[3.31928299e-13 3.37157796e-04 8.96061663e-03]
[ 7.75811083e-10  1.92053635e-01 -1.59316481e+01]
[1.89954261e-13 2.11792047e-04 5.89002792e-02]
[1.29157987e-09 2.19973359e-02 3.14332647e+02]
[6.70174766e-12 1.51763201e-03 4.24845929e+00]


In [42]:
fit_rates1 = []
for temp1 in temps1:
    fit_rate1 = new(temp1, popt1[0], popt1[1], popt1[2])
    fit_rates1.append(fit_rate1)
    
fit_rates2 = []
for temp2 in temps2:
    fit_rate2 = new(temp2, popt2[0], popt2[1], popt2[2])
    fit_rates2.append(fit_rate2)

fit_rates3 = []
for temp3 in temps3:
    fit_rate3 = new(temp3, popt3[0], popt3[1], popt3[2])
    fit_rates3.append(fit_rate3)

fit_rates4 = []
for temp4 in temps4:
    fit_rate4 = new(temp4, popt4[0], popt4[1], popt4[2])
    fit_rates4.append(fit_rate4)

In [43]:
plt.plot(temps1, fit_rates1, label = "fit1")
plt.plot(temps2, fit_rates2, label = "fit2")
plt.plot(temps3, fit_rates3, label = "fit3")
plt.plot(temps4, fit_rates4, label = "fit4")
plt.plot(temps, rates, label = "original")
plt.xscale("log")
plt.yscale("log")
plt.legend()